//---------------------------------------------------------------
// Rest client class definition
//---------------------------------------------------------------
(function(window){
    "use strict";

    const
    	urlBasket = "http://localhost:3000/api/baskets",
    	urlPriceTable = "http://localhost:3000/api/priceTables";

    var RestClient = {};

    //Create a basic GET request and handle the response
    function makeGetRequest(url, callback) {
	    fetch(url, {method: "GET"})
	        .then(response => response.json()) //Transform the data into json
	        .then(callback)
	        .catch(error => console.error(error));
    }

    //Find a new shopping basket randomly generated by the web service
	RestClient.findNextBasket = function(callback) {
		makeGetRequest(urlBasket, callback);
	}

    //Recover the current price table from the web service
	RestClient.findPriceTable = function(callback) {
		makeGetRequest(urlPriceTable, callback);
	}

	window.RestClient = RestClient;

})(window);